# Upptime Configuration for Detectick
# Copy this file to your upptime repository root

owner: carlosvouking # Change this to your GitHub username
repo: detectick-status # Change this to your status repo name

sites:
  - name: Detectick Platform
    url: https://detectick.com

  - name: Detectick API
    url: https://detectick-backend.onrender.com/api/auth/health
    expectedStatusCodes:
      - 200
      - 401 # Health endpoint might return 401 if auth is required

  - name: Bitstamp Exchange
    url: https://www.bitstamp.net/api/v2/trading-pairs-info/
    expectedStatusCodes:
      - 200

  - name: Bitvavo Exchange
    url: https://api.bitvavo.com/v2/time
    expectedStatusCodes:
      - 200

  - name: Coinbase Exchange
    url: https://api.coinbase.com/v2/time
    expectedStatusCodes:
      - 200

  - name: Kraken Exchange
    url: https://api.kraken.com/0/public/SystemStatus
    expectedStatusCodes:
      - 200

  - name: KuCoin Exchange
    url: https://api.kucoin.com/api/v1/timestamp
    expectedStatusCodes:
      - 200

  - name: OKX Exchange
    url: https://www.okx.com/api/v5/public/time
    expectedStatusCodes:
      - 200

status-website:
  # Custom domain setup
  cname: status.detectick.com

  # Branding
  name: Detectick Status
  introTitle: "**Detectick** System Status"
  introMessage: Real-time status of Detectick platform and connected exchanges

  # Navbar links
  navbar:
    - title: Dashboard
      href: https://detectick.com/dashboard
    - title: Main Site
      href: https://detectick.com
    - title: Support
      href: mailto:support@detectick.com

  # Theme
  theme: dark

  # Favicon
  favicon: https://detectick.com/favicon.ico

  # Logo (optional - add your logo URL)
  # logoUrl: https://detectick.com/logo.png

# Monitoring schedule (every 5 minutes)
workflowSchedule:
  uptime: "*/5 * * * *"
  responseTime: "0 */6 * * *"
  graphs: "0 0 * * *"
  staticSite: "0 1 * * *"

# Commit messages
commitMessages:
  readmeContent: ":pencil: Update summary in README [skip ci]"
  summaryJson: ":card_file_box: Update status summary [skip ci]"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci]"
  graphsUpdate: ":bento: Update graphs [skip ci]"

# Assignees for issues (optional)
# assignees:
#   - YOUR_GITHUB_USERNAME

# Notifications (optional - for when services go down)
# notifications:
#   - type: slack
#     webhook-url: $SECRET_SLACK_WEBHOOK_URL
